#ifndef REMOTEOS_SDL_PROTOCOL_H
#define REMOTEOS_SDL_PROTOCOL_H

#define REMOTEOS_PROTOCOL_VERSION 2
#define REMOTEOS_SERVICE_VERSION  "0.2.0"
#define REMOTEOS_MAX_FRAME_BYTES   (16 * 1024 * 1024)
#define REMOTEOS_MAX_BATCH_OPS     4096
#define REMOTEOS_FILE_CHUNK_BYTES  (32 * 1024)

#endif
